#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

#!/usr/bin/env sh

# bar settings
yabai -m config top_padding 0

#global settings
yabai -m config window_placement             second_child
yabai -m config window_topmost               off

yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off

yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.69
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# Mouse support
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config bottom_padding               24
yabai -m config left_padding                 1
yabai -m config right_padding                1
yabai -m config top_padding                  1
yabai -m config window_gap                   8

# float appsod
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add app='Stickies$' manage=off
yabai -m rule --add app='Cisco AnyConnect Secure Mobility Client$' manage=off
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^Logitech G HUB$" manage=off
yabai -m rule --add app="^Finder$" manage=off

function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

setup_space 1 web
setup_space 2 code
setup_space 3 terminal
setup_space 4 notion
setup_space 5 socials
setup_space 6 spotify

# move apps to specific spaces
yabai -m rule --add app='Brave Browser$' space=^1
yabai -m rule --add app='^Code$' space=^2
yabai -m rule --add app='^Notion$' space=^4
yabai -m rule --add app='^iTerm2$' space=^3
yabai -m rule --add app='^Discord|WeChat$' space=^5
yabai -m rule --add app='Spotify$' space=^6
yabai -m rule --add app='zoom.us$' space=^7

# color
yabai -m config window_border on
yabai -m config window_border_width 1
yabai -m config active_window_border_color 0xFF88C0D0
yabai -m config normal_window_border_color 0x002E3440